"""Add Salesforce OAuth and contract links

Revision ID: c30fa7962013
Revises: 34ffdcede661
"""

import sqlalchemy as sa
from alembic import op

revision = "c30fa7962013"
down_revision = "34ffdcede661"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salesforce_connections",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("instance_url", sa.String(length=250), nullable=False),
        sa.Column("access_encrypted", sa.Text(), nullable=False),
        sa.Column("refresh_encrypted", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "salesforce_states",
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("verifier_encrypted", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["tokens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("state_hash"),
    )
    op.create_table(
        "salesforce_links",
        sa.Column("contract_id", sa.String(length=36), nullable=False),
        sa.Column("instance_url", sa.String(length=250), nullable=False),
        sa.Column("opportunity_id", sa.String(length=18), nullable=False),
        sa.Column("opportunity_name", sa.String(length=200), nullable=False),
        sa.Column("linked_by", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["linked_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("contract_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salesforce_links")
    op.drop_table("salesforce_states")
    op.drop_table("salesforce_connections")
    # ### end Alembic commands ###
